##################################################################################################
# jaeger-collector service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  labels:
    app: jaeger-collector
    service: jaeger-collector
spec:
  ports:
    - port: 14250
      name: tcp
      protocol: TCP
  selector:
    app: jaeger-collector
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-headless
  labels:
    app: jaeger-collector-headless
    service: jaeger-collector-headless
spec:
  clusterIP: None # <= Don't forget!!
  ports:
    - port: 14250
      name: tcp
      protocol: TCP
  selector:
    app: jaeger-collector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-collector
  labels:
    account: jaeger-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector-v1
  labels:
    app: jaeger-collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-collector
      version: v1
  template:
    metadata:
      labels:
        app: jaeger-collector
        version: v1
    spec:
      serviceAccountName: jaeger-collector
      containers:
        - name: jaeger-collector
          image: jaegertracing/jaeger-collector:1.21
          volumeMounts:
            - name: certificates
              mountPath: /es/certificates/
              readOnly: true
          args: [ "--es.server-urls=https://elasticsearch-es-http.default.svc:9200",
                  "--es.tls.ca=/es/certificates/ca.crt",
                  "--log-level=debug"]
          ports:
            - name: grpc
              containerPort: 14250
              protocol: TCP
            - name: c-binary-trft
              containerPort: 14268
              protocol: TCP
            - name: zipkin
              containerPort: 9411
              protocol: TCP
            - name: c-tchan-trft
              containerPort: 14267
              protocol: TCP
          env:
            - name: SPAN_STORAGE_TYPE
              value: elasticsearch
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: jaeger-secret
                  key: ES_USERNAME
                  optional: false
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaeger-secret
                  key: ES_PASSWORD
                  optional: false
          securityContext:
            runAsUser: 1000
      volumes:
        - name: certificates
          secret:
            secretName: elasticsearch-es-http-certs-public
---